name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Compile string_sort
      run: |
        gcc -Wall -Werror -Wextra -std=c11 -o ./bin/string_sort ./src/string_sort.c ./src/misc.c
    
    - name: Compile figure_sort if exists
      if: ${{ hashFiles('./src/figure_sort.c') != '' }}
      run: |
        gcc -Wall -Werror -Wextra -std=c11 -o ./bin/figure_sort ./src/figure_sort.c ./src/misc.c

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt

    - name: Run Pytest
      run: |
        pytest --color=yes -v --tb=short --html=pytest_report.html tests

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results
        path: pytest_report.html

    - name: Set up clang-format
      run: |
        sudo apt-get install -y clang-format

    - name: Check code style with clang-format
      run: |
        if clang-format -n --Werror $(find src/ -name '*.c' -o -name '*.h'); then
          echo "clang-format check passed"
        else
          echo "clang-format check failed. Hey, frogger, use clang-format to fix the style issues."
          exit 1
        fi

    - name: Set up cppcheck
      run: |
        sudo apt install cppcheck

    - name: Check code with cppcheck
      run: |
        cppcheck --enable=all --suppress=missingIncludeSystem --error-exitcode=1 $(find src/ -name '*.c' -o -name '*.h')